version: "3"
services:
  db:
    image: postgres:11.6
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    networks:
      app_net:
        ipv4_address: 172.16.238.14
  redis:
    image: redis:5.0.7
    volumes:
      - redis:/data
    networks:
      app_net:
        ipv4_address: 172.16.238.13
  smtp:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp
      - 8025:8025 # web UI
    restart: always
    networks:
      app_net:
        ipv4_address: 172.16.238.12
  webhookrelay:
    image: webhookrelay/webhookrelayd
    environment:
      - KEY=009eecfc-1bae-45eb-98be-112f9335238c
      - SECRET=1t4kAEItAYJF
      - BUCKET=formsling-development
      - INSECURE=true
    networks:
      app_net:
        ipv4_address: 172.16.238.11
  app:
    build: .
    command: bash -c "rm -rf ./tmp/pids/*.pid && foreman start -f Procfile.dev-server"
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    ports:
      - "3000:3000" # rails s
      - "3035:3035" # webpack-dev-server
    environment:
      - DATABASE_URL=postgres://postgres@db
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
      - RAILS_ENV=development
      - RACK_ENV=development
      - NODE_ENV=development
    depends_on:
      - db
      - redis
    networks:
      app_net:
        ipv4_address: 172.16.238.10

volumes:
  postgres:
  redis:
  bundle:
  node_modules:
  rails_cache:
  packs:

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
